# Pickling and Unpickling


The pickle module implements binary protocols for serializing and de-serializing a Python object structure. “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream (from a binary file or bytes-like object) is converted back into an object hierarchy. Pickling (and unpickling) is alternatively known as “serialization”, “marshalling,” 1 or “flattening”; however, to avoid confusion, the terms used here are “pickling” and “unpickling”.

Pickle in Python is primarily used in serializing and deserializing a Python object structure. In other words, it's the process of converting a Python object into a byte stream to store it in a file/database, maintain program state across sessions, or transport data over the network

Extentions


.pkl Files:
.pkl is a common file extension used to indicate that the file contains a serialized Python object using the pickle library.
It's a general-purpose extension used for any kind of pickled Python object.
.pkl files can store a wide range of Python objects, including custom classes, data structures, and even entire models.
The pickle module in Python is used to serialize and deserialize objects into and from .pkl files.
.pkl files are not tied to any specific library or purpose, so they are versatile for saving and loading various types of objects.

.sav Files:
.sav is often used as a file extension to indicate that the file contains a serialized object, particularly when dealing with machine learning models or data preprocessing components.
While .sav files can be created using the pickle library, in some contexts, they might be more commonly associated with specific libraries like scikit-learn.
For example, in the context of scikit-learn, .sav files are used to store models, transformers, and pipelines using the joblib library, which is a more efficient alternative to pickle for large data arrays.
The joblib library is similar to pickle but optimized for numerical arrays often encountered in machine learning.

In [7]:
import seaborn as sns

In [9]:
tips = sns.load_dataset('tips')

In [10]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
import pickle

In [12]:
filename = 'tips.pkl'

In [13]:
pickle.dump(tips, open(filename,'wb'))

In [14]:
pickle.load(open(filename,'rb'))

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]